### ISSUE TITLE
Using GPG key as SSH-Key

### ISSUE THREAD

**Issue by PaBLoX-CL** [terlar/dotfiles#3]
Continuing part of the discussion from here: https://github.com/pbrisbin/dotfiles/commit/6770e006de8d12616532c7a1242d95296740f692#commitcomment-8980499

I read that you used envoy, since gnupg 2.1 can even use gpg keys for authentication for ssh. Since I read your suggestion, I manage to make everything work, without envoy, so I'm wondering its use :).

**Comment by terlar** [comment]
Sorry for never getting back on this, but you are right, with the new GnuPG 2.1 and everything this is unneeded. All working very well out of the box. This was some glue that was neat in the in-between stages. Especially before the GnuPG started an agent on first connect. Then this service took care of starting up the GPG Agent and letting it run between login sessions.

**Comment by PaBLoX-CL** [comment]
Nevermind ;)
